version: "2.2"

services:
  plex:
    container_name: plex
    environment:
      PGID: 978
      TZ: America/Denver
      VERSION: latest
    image: linuxserver/plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - /storage/plex/config:/config
      - /storage/tvshows:/data/tvshows
      - /storage/movies:/data/movies
      - /storage/home_videos:/data/home_videos
      - /storage/plex/transcode:/transcode

  unifi:
    cap_add:
      - SYS_ADMIN
    container_name: unifi
    environment:
      RUNAS_UID0: 'false'
      TZ: America/Denver
      UNIFI_GID: 750
      UNIFI_UID: 750
    hostname: 'unifi'
    # image: ryanmt/unifi:unstable
    image: jacobalberty/unifi:stable
    init: true
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:unifi.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
      - "traefik.backend=unifi"
      - "traefik.port=8080"
    networks:
      - web
    ports:
      - '3478:3478/udp'
      # - '6789:6789'
      - '8080:8080'
      - '8443:8443'
      - '8843:8843'
      - '10001:10001/udp'
    restart: unless-stopped
    volumes:
      - /storage/unifi/config:/unifi/data
      - /storage/unifi/logs:/unifi/log
      - /storage/unifi/cert:/unifi/cert
      - /storage/unifi/init_scripts:/unifi/init.d

  unifi_video:
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    container_name: unifi_video
    environment:
      TZ: America/Denver
      PGID: 10000
      PUID: 1000
    image: pducharme/unifi-video-controller
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:cameras.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
      - "traefik.backend=unifi_video"
      - "traefik.port=7080"
    networks:
      - web
    ports:
      - '7442:7442'
      - '7443:7443'
      - '7445:7445'
      - '7446:7446'
      - '7447:7447'
      - '7080:7080'
      - '6666:6666'
    # restart: unless-stopped
    volumes:
      - /storage/unifi_camera/config:/var/lib/unifi-video
      - /storage/unifi_camera/videos:/usr/lib/unifi-video/data/videos
      - /storage/unifi_camera/logs:/var/log/unifi-video

  pi_hole:
    cap_add:
      - NET_ADMIN
    container_name: pi_hole
    environment:
      ServerIP: 192.168.1.2
      VIRTUAL_HOST: "pihole.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
      WEBPASSWORD: 942c98b
    image: pihole/pihole:latest
    labels:
      - "traefik.backend=pihole"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.priority=1"
      - "traefik.frontend.rule=HostRegexp:pihole.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
      - "traefik.port=80"
      - "traefik.protocol=http"
    networks:
      - web
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8081:80'
      - '9443:443'
    restart: unless-stopped
    volumes:
      - /storage/pihole/pihole/:/etc/pihole/
      - /storage/pihole/dnsmasq.d/:/etc/dnsmasq.d/

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp:nextcloud.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
      - "traefik.backend=nextcloud"
      - "traefik.port=8881"
    networks:
      - web
    ports:
      - 8881:80
    restart: unless-stopped
    volumes:
      - /storage/nextcloud:/var/www/html

  traefik:
    container_name: traefik
    dns:
      - 8.8.8.8
      # - 192.168.1.2
    image: traefik:1.7
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /opt/traefik/acme.json:/acme.json
      - /opt/traefik/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:chat.29e0822e-d0cc-11e7-8fab-cec278b6b50a.ryanmt.me"
    networks:
      - web

networks:
  web:
    external: true
